# Generated by Django 4.2.5 on 2026-01-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_examsession_exam_data_examassignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("FAILED", "Failed"),
                    ("CONFIGURATION", "Configuration"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
