# Generated by Django 4.2.5 on 2026-01-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_examassignment_result_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="examassignment",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
